"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Settings={enabled:boolean;confirmation_mode:"instant"|"manual";allow_secure_history:boolean;welcome_message:string;session_timeout_minutes:number;waitlist_offer_minutes:number;patient_portal_base_url:string};
const defaults:Settings={enabled:false,confirmation_mode:"instant",allow_secure_history:true,welcome_message:"Welcome. I can help you book an appointment, view an existing booking, or request human assistance.",session_timeout_minutes:30,waitlist_offer_minutes:30,patient_portal_base_url:"https://omnirelay-light.alam-kkhurshid.chatgpt.site"};

type BookingRequest={id:string;patient_name:string|null;starts_at:string;status:string;service?:{name:string}|null;location?:{name:string}|null};
type BookingSession={context?:{returning_patient?:boolean}|null};
type WaitlistOffer={created_at:string;starts_at:string;status:string};
type WaitlistEntry={id:string;patient_name:string;service?:{name:string}|null;location?:{name:string}|null;priority:number;status:string;offers?:WaitlistOffer[]|null;offer_expires_at?:string|null};

function latestOffer(item:WaitlistEntry){return [...(item.offers??[])].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())[0]}
function remaining(expiresAt:string|undefined,now:number){if(!expiresAt)return "";const seconds=Math.max(0,Math.floor((new Date(expiresAt).getTime()-now)/1000));return `${Math.floor(seconds/60)}m ${String(seconds%60).padStart(2,"0")}s`}

export function BookingConciergeWorkspace({organizationId,initialSettings,requests,sessions,waitlist,locationCount,serviceCount}:{organizationId:string;initialSettings:Partial<Settings>|null;requests:BookingRequest[];sessions:BookingSession[];waitlist:WaitlistEntry[];locationCount:number;serviceCount:number}){
  const [form,setForm]=useState<Settings>({...defaults,...(initialSettings??{})}); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [testInput,setTestInput]=useState("hi"); const [deciding,setDeciding]=useState(""); const [now,setNow]=useState(()=>Date.now());
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
  const recognized=sessions.filter(session=>Boolean(session.context?.returning_patient)).length;
  const testReply=useMemo(()=>testInput.trim()==="4"?"Repeat your last appointment?\nConsultation\nChamber 1\nPrimary provider\n\n1. Continue and choose a new date\n2. Start a different booking":testInput.trim()==="1"?"Choose a service from the live clinic catalogue.":testInput.trim()==="5"?"Doctor directory & clinic brochure (PDF)\n\nThe current clinic directory opens as a public PDF.":testInput.trim()==="6"?"Clinic timings & location\n\nCurrent clinic locations and recorded doctor timings are shown here.":testInput.trim()==="7"?"The recorded clinic front-desk number is shown here.":`${form.welcome_message}\n\n1. Choose appointment (Recommended)\n2. My bookings\n3. Last visit / prescription\n4. Repeat my last appointment\n5. Doctor directory & brochure\n6. Clinic timings & location\n7. Speak to front desk\n9. Human assistance`,[testInput,form.welcome_message]);
  async function save(){setSaving(true);setNotice("");const {error}=await createClient().from("whatsapp_booking_settings").upsert({organization_id:organizationId,...form,updated_at:new Date().toISOString()},{onConflict:"organization_id"});setNotice(error?error.message:"Concierge settings saved.");setSaving(false)}
  async function decide(requestId:string,decision:"approve"|"reject"|"waitlist"){setDeciding(requestId);setNotice("");const note=decision==="approve"?"Approved by clinic team":decision==="waitlist"?"Requested time unavailable; patient retained for the next suitable opening":"Requested slot unavailable";const {error}=await createClient().rpc("decide_whatsapp_booking_request",{p_organization_id:organizationId,p_request_id:requestId,p_decision:decision,p_note:note});if(error){setNotice(error.message);setDeciding("");return}window.location.reload()}
  return <div className="module-page concierge-page">
    <section className="module-hero concierge-hero"><div><span className="app-eyebrow">WHATSAPP BOOKING CONCIERGE</span><h2>Turn every “Hi” into a safe booking journey.</h2><p>Patients choose a service, chamber, doctor and only currently available time slots. Medical history stays behind mobile verification.</p></div><div className={`concierge-status ${form.enabled?"on":""}`}><i/> {form.enabled?"Ready to receive":"Not live"}</div></section>
    <section className="concierge-metrics"><article><span>Chambers</span><b>{locationCount}</b><small>Location-specific schedules</small></article><article><span>Bookable services</span><b>{serviceCount}</b><small>Live catalogue</small></article><article><span>Returning patients</span><b>{recognized}</b><small>Recognized in recent sessions</small></article><article><span>Waiting patients</span><b>{waitlist.filter(x=>x.status==="waiting").length}</b><small>Priority then request time</small></article></section>
    <div className="concierge-grid"><section className="foundation-section"><header><div><span className="app-eyebrow">CONTROL</span><h2>Booking policy</h2></div><span className="section-status">RLS protected</span></header><div className="form-grid">
      <label className="wide concierge-toggle"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span><b>Enable WhatsApp concierge</b><small>Incoming WhatsApp greetings start the guided journey.</small></span></label>
      <label>Confirmation mode<select value={form.confirmation_mode} onChange={e=>setForm({...form,confirmation_mode:e.target.value as Settings["confirmation_mode"]})}><option value="instant">Instant booking</option><option value="manual">Doctor/assistant approval</option></select></label>
      <label>Session timeout<select value={form.session_timeout_minutes} onChange={e=>setForm({...form,session_timeout_minutes:Number(e.target.value)})}><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label>
      <label>Waitlist offer expiry<select value={form.waitlist_offer_minutes} onChange={e=>setForm({...form,waitlist_offer_minutes:Number(e.target.value)})}><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label>
      <label className="wide">Welcome message<textarea value={form.welcome_message} onChange={e=>setForm({...form,welcome_message:e.target.value})}/></label>
      <label className="wide">Secure patient portal URL<input type="url" value={form.patient_portal_base_url} onChange={e=>setForm({...form,patient_portal_base_url:e.target.value.replace(/\/$/,"")})}/><small className="field-help">Keep the current address until OmniRelay moves to its custom domain.</small></label>
      <label className="wide concierge-toggle"><input type="checkbox" checked={form.allow_secure_history} onChange={e=>setForm({...form,allow_secure_history:e.target.checked})}/><span><b>Offer bookings and approved records</b><small>WhatsApp verifies possession of the registered number, then sends a short-lived secure link. Records never appear directly in chat.</small></span></label>
    </div><button className="primary-button compact-action" onClick={save} disabled={saving}>{saving?"Saving…":"Save concierge settings"}</button>{notice&&<p className="form-message">{notice}</p>}</section>
    <section className="phone-simulator"><header><i>●</i><div><b>OmniRelay Booking</b><small>WhatsApp Business</small></div></header><div className="phone-chat"><div className="incoming">{testReply.split("\n").map((x,i)=><span key={i}>{x||<br/>}</span>)}</div></div><div className="phone-input"><input value={testInput} onChange={e=>setTestInput(e.target.value)} aria-label="Test patient reply"/><button>→</button></div><small>This simulator sends no patient message.</small></section></div>
    <section className="data-panel" id="booking-requests"><header><div><span className="app-eyebrow">OPERATIONS</span><h3>Booking requests</h3></div><span className="section-status">{requests.filter(r=>r.status==="pending_approval").length} awaiting decision</span></header>{requests.length===0?<div className="concierge-empty">Requests will appear here when patients complete the WhatsApp journey.</div>:requests.map(r=><div className="data-row booking-request-row" key={r.id}><b>{r.patient_name||"Patient"}<small>{r.service?.name||"Service"} · {r.location?.name||"Location"} · {new Date(r.starts_at).toLocaleString("en-IN")}</small></b><span className={`request-state ${r.status}`}>{r.status.replace("_"," ")}</span>{r.status==="pending_approval"&&<div className="request-actions"><button onClick={()=>decide(r.id,"approve")} disabled={deciding===r.id}>Approve</button><button onClick={()=>decide(r.id,"waitlist")} disabled={deciding===r.id}>Waitlist</button><button className="reject" onClick={()=>decide(r.id,"reject")} disabled={deciding===r.id}>Reject</button></div>}</div>)}{notice&&<p className="form-message">{notice}</p>}</section>
    <section className="data-panel waitlist-panel"><header><div><span className="app-eyebrow">AUTOMATED CAPACITY RECOVERY</span><h3>Waitlist offers</h3></div><span className="section-status">{waitlist.filter(x=>x.status==="waiting").length} waiting · {waitlist.filter(x=>x.status==="offered").length} offered</span></header>{waitlist.length===0?<div className="concierge-empty">Patients retained for an unavailable slot will appear here. A cancellation automatically offers the slot to the highest-priority match.</div>:waitlist.map(item=>{const offer=latestOffer(item);return <div className="data-row waitlist-row" key={item.id}><b>{item.patient_name}<small>{item.service?.name||"Service"} · {item.location?.name||"Any chamber"} · priority {item.priority}</small>{offer&&<small>Slot: {new Date(offer.starts_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</small>}</b><div className="waitlist-state"><span className={`request-state ${item.status}`}>{item.status}</span>{item.status==="offered"&&<strong className="offer-countdown">Expires in {remaining(item.offer_expires_at,now)}</strong>}{offer&&<small>Offer {offer.status}</small>}</div></div>})}</section>
    <section className="concierge-safety"><b>Patient safety boundary</b><span>The concierge can schedule care. It cannot diagnose, recommend medicines, or expose clinical records in chat. Urgent or clinical messages are handed to a human.</span></section>
  </div>
}
