"use client";
import { useState } from "react";

export type SecurityIncident = { id:string; reference:string; severity:string; category:string; status:string; title:string; safe_summary:string; containment_summary:string|null; resolution_summary:string|null; created_at:string; updated_at:string };

export function IncidentControl({ initialIncidents, canManage }: { initialIncidents: SecurityIncident[]; canManage: boolean }) {
  const [incidents,setIncidents]=useState(initialIncidents); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [form,setForm]=useState({title:"",safeSummary:"",severity:"medium",category:"service_outage"});
  async function createIncident(event:React.FormEvent){event.preventDefault();setBusy("create");setError("");setMessage("");const response=await fetch("/api/operations/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json();setBusy("");if(!response.ok){setError(result.error??"Incident could not be created.");return}setIncidents(current=>[result.incident,...current]);setOpen(false);setForm({title:"",safeSummary:"",severity:"medium",category:"service_outage"});setMessage(`${result.incident.reference} opened and assigned.`)}
  async function updateIncident(incident:SecurityIncident,status:string){const resolutionSummary=["resolved","closed"].includes(status)?window.prompt("Add a safe resolution summary. Do not include patient names or medical details.")?.trim():undefined;const containmentSummary=status==="contained"?window.prompt("Add a safe containment summary. Do not include patient names or medical details.")?.trim():undefined;if(["resolved","closed"].includes(status)&&!resolutionSummary)return;if(status==="contained"&&!containmentSummary)return;setBusy(incident.id);setError("");setMessage("");const response=await fetch("/api/operations/incidents",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:incident.id,status,resolutionSummary,containmentSummary})});const result=await response.json();setBusy("");if(!response.ok){setError(result.error??"Incident could not be updated.");return}setIncidents(current=>current.map(item=>item.id===incident.id?result.incident:item));setMessage(`${result.incident.reference} moved to ${result.incident.status}.`)}
  const active=incidents.filter(item=>!["resolved","closed"].includes(item.status));
  return <section className="security-incident-control"><header><div><span className="app-eyebrow">PILOT GOVERNANCE</span><h3>Security incident register</h3><p>Record operational and security events without patient names, phone numbers or medical content.</p></div>{canManage&&<button onClick={()=>setOpen(!open)}>{open?"Cancel":"Open incident"}</button>}</header>{message&&<p className="incident-success" role="status">✓ {message}</p>}{error&&<p className="incident-error" role="alert">{error}</p>}
  {open&&<form className="incident-form" onSubmit={createIncident}><label>Safe title<input required minLength={5} maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Example: WhatsApp delivery interruption"/></label><div><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="service_outage">Service outage</option><option value="provider_failure">Provider failure</option><option value="suspicious_activity">Suspicious activity</option><option value="unauthorized_access">Unauthorized access</option><option value="credential_compromise">Credential compromise</option><option value="data_exposure">Data exposure</option><option value="other">Other</option></select></label></div><label>Safe summary<textarea required minLength={5} maxLength={1000} value={form.safeSummary} onChange={e=>setForm({...form,safeSummary:e.target.value})} placeholder="Describe impact and immediate action without patient-identifying information."/></label><button disabled={busy==="create"}>{busy==="create"?"Opening…":"Open and assign to me"}</button></form>}
  {active.length?<div className="incident-list">{active.map(incident=><article key={incident.id} className={`severity-${incident.severity}`}><div><span>{incident.reference} · {incident.severity}</span><b>{incident.title}</b><small>{incident.safe_summary}</small></div><em>{incident.status}</em>{canManage&&<nav>{incident.status==="open"&&<button disabled={busy===incident.id} onClick={()=>updateIncident(incident,"contained")}>Contain</button>}{incident.status==="contained"&&<button disabled={busy===incident.id} onClick={()=>updateIncident(incident,"monitoring")}>Monitor</button>}<button disabled={busy===incident.id} onClick={()=>updateIncident(incident,"resolved")}>Resolve</button></nav>}</article>)}</div>:<div className="operations-empty"><i>✓</i><b>No active security incidents</b><span>The clinic pilot has no open incident records.</span></div>}</section>;
}
