"use client";

import { useMemo, useState } from "react";

type MemberExtra = { role?:string; clinic_role?:string; status?:string; invitation?:{ status?:string; email?:string } };
type Member = { id:string; user_id:string|null; name:string; picture:string|null; extra:MemberExtra|null; created_at:string };
type Task = { id:string; patient_id:string; care_plan_id:string|null; title:string; details:string|null; due_at:string|null; priority:string; status:string; assigned_to:string|null; created_at:string };
type Patient = { id:string; full_name:string };
type Notification = { id:string; notification_type:string; title:string; body:string|null; href:string|null; read_at:string|null; created_at:string };
type AuditEvent = { id:string; event_type:string; summary:string; created_at:string };
type OperationalEvent = { id:string; event_source:string; severity:string; error_code:string; safe_message:string; resolved_at:string|null; created_at:string };
const accessLabel:Record<string,string>={owner:"Owner",admin:"Admin",member:"Member"};
const clinicLabel:Record<string,string>={owner:"Clinic owner",doctor:"Doctor",receptionist:"Receptionist",assistant:"Assistant"};

export function TeamOperations({currentUserId,currentRole,members:initialMembers,tasks:initialTasks,patients,notifications:initialNotifications,auditEvents,operationalEvents}:{currentUserId:string;currentRole:string;members:Member[];tasks:Task[];patients:Patient[];notifications:Notification[];auditEvents:AuditEvent[];operationalEvents:OperationalEvent[]}){
 const [members,setMembers]=useState(initialMembers),[tasks,setTasks]=useState(initialTasks),[notifications,setNotifications]=useState(initialNotifications);
 const [inviteOpen,setInviteOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[view,setView]=useState<"mine"|"all">("mine");
 const [invite,setInvite]=useState({name:"",email:"",accessRole:"member",clinicRole:"assistant"});
 const patientNames=useMemo(()=>Object.fromEntries(patients.map((item)=>[item.id,item.full_name])),[patients]);
 const visibleTasks=tasks.filter((task)=>view==="all"||task.assigned_to===currentUserId),activeMembers=members.filter((member)=>member.user_id&&member.extra?.status!=="disabled"),pendingMembers=members.filter((member)=>!member.user_id&&member.extra?.invitation?.status==="pending");
 async function inviteMember(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/team/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(invite)});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error??"Invitation failed.");return}setMembers((current)=>[...current,data.member]);setInvite({name:"",email:"",accessRole:"member",clinicRole:"assistant"});setInviteOpen(false);setMessage(data.delivery==="existing_user"?"Invitation recorded. Ask this existing OmniRelay user to sign in again.":"Secure invitation email sent.")}
 async function updateMember(member:Member,accessRole:string,clinicRole:string){setBusy(true);setMessage("");const response=await fetch("/api/team/members",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,accessRole,clinicRole})});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error??"Role update failed.");return}setMembers((current)=>current.map((item)=>item.id===member.id?data.member:item));setMessage("Team permissions updated.")}
 async function deactivateMember(member:Member){const pending=!member.user_id&&member.extra?.invitation?.status==="pending";if(!window.confirm(pending?`Revoke the invitation for ${member.name}?`:`Deactivate ${member.name}? They will immediately lose workspace access.`))return;setBusy(true);setMessage("");const response=await fetch(`/api/team/members?id=${member.id}`,{method:"DELETE"});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error??"Member could not be deactivated.");return}setMembers((current)=>current.map((item)=>item.id===member.id?data.member:item));setMessage(pending?"Invitation revoked.":"Team member deactivated. Their record and audit history were retained.")}
 async function reactivateMember(member:Member){setBusy(true);setMessage("");const response=await fetch("/api/team/members",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,action:"reactivate"})});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error??"Member could not be reactivated.");return}setMembers((current)=>current.map((item)=>item.id===member.id?data.member:item));setMessage("Team member reactivated.")}
 async function updateTask(task:Task,status:string){setBusy(true);setMessage("");const response=await fetch("/api/patients/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:task.id,status})});const data=await response.json();setBusy(false);if(!response.ok){setMessage(data.error??"Task could not be updated.");return}setTasks((current)=>current.map((item)=>item.id===task.id?data.task:item))}
 async function markNotificationsRead(){const response=await fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});if(response.ok)setNotifications((current)=>current.map((item)=>item.notification_type==="serious_action"?item:{...item,read_at:item.read_at??new Date().toISOString()}))}
 return <div className="team-operations"><section className="team-hero"><div><span className="app-eyebrow">CLINIC OPERATIONS</span><h2>One team, clear ownership.</h2><p>Invite staff, separate clinic duties from workspace permissions, and make every patient-care task accountable.</p></div>{currentRole==="owner"&&<button className="primary-link" onClick={()=>setInviteOpen(true)}>Invite team member</button>}</section>{message&&<p className="form-message" role="status">{message}</p>}
 <div className="team-metrics"><article><span>Active staff</span><b>{activeMembers.length}</b><small>Signed-in workspace members</small></article><article><span>Pending invites</span><b>{pendingMembers.length}</b><small>Awaiting secure acceptance</small></article><article><span>My open tasks</span><b>{tasks.filter((task)=>task.assigned_to===currentUserId&&!["completed","cancelled"].includes(task.status)).length}</b><small>Assigned directly to you</small></article><article><span>Unread alerts</span><b>{notifications.filter((item)=>!item.read_at).length}</b><small>Private to your account</small></article></div>
 <div className="team-grid"><section className="team-card"><header><div><span className="app-eyebrow">STAFF DIRECTORY</span><h3>Workspace team</h3></div><small>{currentRole==="owner"?"Owner controls access":"Read-only directory"}</small></header><div className="member-list">{members.map((member)=>{const role=String(member.extra?.role??"member"),clinicRole=String(member.extra?.clinic_role??(role==="owner"?"owner":"assistant")),disabled=member.extra?.status==="disabled",pending=!member.user_id&&member.extra?.invitation?.status==="pending",locked=role==="owner"||currentRole!=="owner"||disabled;return <article className={disabled?"member-disabled":""} key={member.id}><div className="member-avatar">{member.name.slice(0,1).toUpperCase()}</div><div><b>{member.name}</b><span>{disabled?(member.user_id?"Deactivated · access blocked":"Invitation revoked"):member.user_id?clinicLabel[clinicRole]:`Invite pending · ${member.extra?.invitation?.email??""}`}</span></div><select aria-label={`${member.name} clinic role`} disabled={locked||busy} value={clinicRole} onChange={(e)=>updateMember(member,role,e.target.value)}><option value="doctor">Doctor</option><option value="receptionist">Receptionist</option><option value="assistant">Assistant</option>{role==="owner"&&<option value="owner">Clinic owner</option>}</select><select aria-label={`${member.name} access role`} disabled={locked||busy} value={role} onChange={(e)=>updateMember(member,e.target.value,clinicRole)}><option value="member">Member</option><option value="admin">Admin</option>{role==="owner"&&<option value="owner">Owner</option>}</select>{currentRole==="owner"&&role!=="owner"?(disabled&&member.user_id?<button className="reactivate-member" disabled={busy} onClick={()=>reactivateMember(member)}>Reactivate</button>:<button className="remove-member" disabled={busy} onClick={()=>deactivateMember(member)}>{pending?"Revoke":"Deactivate"}</button>):<i>{accessLabel[role]}</i>}</article>})}</div></section>
 <section className="team-card task-board"><header><div><span className="app-eyebrow">CARE QUEUE</span><h3>{view==="mine"?"My tasks":"All tasks"}</h3></div><div className="segmented"><button className={view==="mine"?"active":""} onClick={()=>setView("mine")}>Mine</button><button className={view==="all"?"active":""} onClick={()=>setView("all")}>All</button></div></header><div className="task-list">{visibleTasks.length?visibleTasks.map((task)=><article className={`priority-${task.priority}`} key={task.id}><div><span>{task.care_plan_id?"care plan review":task.priority}</span><b>{task.title}</b><small>{patientNames[task.patient_id]??"Patient"}{task.due_at?` · due ${new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(task.due_at))}`:""}</small></div><select disabled={busy||(currentRole==="member"&&task.assigned_to!==currentUserId)} value={task.status} onChange={(e)=>updateTask(task,e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></article>):<p className="empty-note">No tasks in this view.</p>}</div></section>
 <section className="team-card notification-card"><header><div><span className="app-eyebrow">IN-APP ALERTS</span><h3>Your notifications</h3></div>{notifications.some((item)=>!item.read_at)&&<button onClick={markNotificationsRead}>Mark all read</button>}</header><div className="notification-feed">{notifications.length?notifications.map((item)=><article className={item.read_at?"":"unread"} key={item.id}><i></i><div><b>{item.title}</b><span>{item.body}</span><time>{new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(item.created_at))}</time></div></article>):<p className="empty-note">You are all caught up.</p>}</div></section>
 {currentRole!=="member"&&<section className="team-card audit-card"><header><div><span className="app-eyebrow">ACCESS AUDIT</span><h3>Recent team changes</h3></div><small>Append-only history</small></header><div className="audit-feed">{auditEvents.length?auditEvents.map((item)=><article key={item.id}><i></i><div><b>{item.summary}</b><span>{item.event_type.replaceAll("_"," ")}</span></div><time>{new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(item.created_at))}</time></article>):<p className="empty-note">Team changes will appear here.</p>}</div></section>}
 {currentRole!=="member"&&<section className={`team-card health-card ${operationalEvents.length?"attention":"healthy"}`}><header><div><span className="app-eyebrow">OPERATIONS HEALTH</span><h3>{operationalEvents.length?`${operationalEvents.length} item${operationalEvents.length===1?"":"s"} need attention`:"All monitored services healthy"}</h3></div><i>{operationalEvents.length?"!":"✓"}</i></header>{operationalEvents.length?<div className="health-feed">{operationalEvents.map((item)=><article key={item.id}><b>{item.safe_message}</b><span>{item.event_source} · {item.error_code}</span><time>{new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(item.created_at))}</time></article>)}</div>:<p>No unresolved team-operation errors have been recorded.</p>}</section>}</div>
 {inviteOpen&&<div className="modal-backdrop" onClick={()=>setInviteOpen(false)}><form className="team-invite-modal" onClick={(e)=>e.stopPropagation()} onSubmit={inviteMember}><header><div><span className="app-eyebrow">SECURE INVITATION</span><h3>Add clinic staff</h3></div><button type="button" onClick={()=>setInviteOpen(false)}>×</button></header><p>The invitation is tied to this workspace. The recipient signs in securely and receives only the access selected below.</p><label>Full name<input required minLength={2} value={invite.name} onChange={(e)=>setInvite({...invite,name:e.target.value})}/></label><label>Work email<input required type="email" value={invite.email} onChange={(e)=>setInvite({...invite,email:e.target.value})}/></label><div><label>Clinic duty<select value={invite.clinicRole} onChange={(e)=>setInvite({...invite,clinicRole:e.target.value})}><option value="doctor">Doctor</option><option value="receptionist">Receptionist</option><option value="assistant">Assistant</option></select></label><label>Workspace access<select value={invite.accessRole} onChange={(e)=>setInvite({...invite,accessRole:e.target.value})}><option value="member">Member</option><option value="admin">Admin</option></select></label></div><small>Admins can configure clinical operations. Members can work assigned tasks and daily workflows.</small><button className="primary-button" disabled={busy}>{busy?"Sending securely…":"Send invitation"}</button></form></div>}</div>
}
