"use client";
import { useState } from "react";

const Mark=()=> <span className="mark"><i/><i/></span>;
// The supplied brand raster is intentionally rendered directly in Sites/Vinext.
// eslint-disable-next-line @next/next/no-img-element
const Logo=()=> <a href="#" className="logo asset-logo"><img src="/omnirelay-logo.jpeg" alt="OmniRelay"/></a>;
const features=[
  ["✦","AI Conversations","Turn every customer interaction into a fast, personal response—across every channel."],
  ["⌁","Workflow Automation","Connect decisions to action with intelligent workflows that move work forward automatically."],
  ["◎","Unified Intelligence","Bring your teams, data and systems into one clear operating view, ready for every next move."]
];
const flows=[
  ["SUPPORT","Resolve customer requests before they become tickets.","OmniRelay understands intent, finds the right context and responds across every channel—then hands off with the full story."],
  ["OPERATIONS","Turn routine work into reliable, autonomous flows.","Route approvals, update records and keep every team aligned without constant follow-up."],
  ["GROWTH","Know the next best action for every customer.","Unify signals across your stack and help teams act on the moments that matter."]
];
export default function Home(){
 const [menu,setMenu]=useState(false); const [flow,setFlow]=useState(0);
 return <main>
  <nav className="nav shell"><Logo/><div className={"links "+(menu?"open":"")}><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#results">Results</a><a href="#impact">Impact</a><a href="/about">About</a><a href="/login">Sign in</a></div><a className="btn dark navbtn" href="/login">Start free trial ↗</a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu"><i/><i/></button></nav>
  <section className="hero shell">
   <div className="heroCopy"><span className="eyebrow">● THE AI OPERATING LAYER FOR BUSINESS</span><h1>One system.<br/>Every conversation.<br/><em>Infinite momentum.</em></h1><p>Connect your teams, customers and workflows in one intelligent operating system—so your business can respond, decide and grow without limits.</p><div className="actions"><a className="btn gradient" href="#demo">Book a demo ↗</a><a href="#platform" className="explore">Explore the platform ↓</a></div><div className="proof"><span>KA</span><span>MR</span><span>JS</span><b>98.5% <small>resolution rate across teams</small></b></div></div>
   <div className="visual"><div className="orbit a"/><div className="orbit b"/><div className="dash"><header><Mark/><small>LIVE OVERVIEW</small><i/></header><div className="welcome"><small>GOOD MORNING, KHURSHID</small><h3>Your business is moving.</h3></div><div className="metrics"><article><span>Conversations</span><b>12,540</b><small>↑ 16.6%</small></article><article><span>Resolved</span><b>98.5%</b><small>↑ 12.4%</small></article></div><div className="chart"><span>Momentum</span><div>{[30,52,43,70,58,83,69,96].map((x,i)=><i key={i} style={{height:x+"%"}}/>)}</div></div><section className="activity"><small>LIVE ACTIVITY</small><p><i>✓</i><b>Customer resolved</b><span>Now</span></p><p><i>⌁</i><b>Workflow completed</b><span>2m</span></p><p><i>✦</i><b>Insight generated</b><span>5m</span></p></section></div><div className="signal"><small>AI SIGNAL</small><b>Opportunity detected</b><span>Enterprise account · High intent</span></div><div className="resolved">✓ <b>98.5%<small>Resolved</small></b></div></div>
  </section>
  <section className="cloud shell"><small>TRUSTED BY FORWARD-THINKING TEAMS</small><div><b>ACME</b><b>NEXORA</b><b>Vertex</b><b>◈ PULSAR</b><b>gridline</b></div></section>
  <section className="platform shell section" id="platform"><div className="heading"><div><span className="eyebrow">THE PLATFORM</span><h2>Everything your business needs<br/>to move as <em>one.</em></h2></div><p>OmniRelay replaces disconnected tools with a single intelligent layer—built to understand, coordinate and act across your entire business.</p></div><div className="cards">{features.map((f,i)=><article key={f[1]}><i className={"fi f"+i}>{f[0]}</i><h3>{f[1]}</h3><p>{f[2]}</p><a href="#solutions">Explore capability ↗</a></article>)}</div></section>
  <section className="flows" id="solutions"><div className="shell flowgrid"><div><span className="eyebrow">BUILT AROUND YOUR BUSINESS</span><h2>From signal to action,<br/><em>without the friction.</em></h2><div className="tabs">{flows.map((f,i)=><button key={f[0]} className={flow===i?"active":""} onClick={()=>setFlow(i)}>0{i+1} {f[0]}</button>)}</div><div className="flowcopy"><small>{flows[flow][0]}</small><h3>{flows[flow][1]}</h3><p>{flows[flow][2]}</p></div></div><div className="flowview"><div className="source">✉ <b>New customer signal<small>Intent identified</small></b></div><span className="line">AI ORCHESTRATION</span><div className="hub"><Mark/><small>OmniRelay AI</small><b>Understands. Decides. Acts.</b></div><div className="out"><span>✓ <b>Resolved</b></span><span>↗ <b>Updated</b></span><span>✦ <b>Learned</b></span></div></div></div></section>
  <section className="section shell" id="results"><div className="results"><span className="eyebrow">THE OMNIRELAY EFFECT</span><h2>Less busywork.<br/>More <em>momentum.</em></h2><div className="stats"><div><b>98.5%</b><span>Conversations resolved automatically</span></div><div><b>64%</b><span>Less repetitive work</span></div><div><b>3.2×</b><span>Faster signal to action</span></div></div></div></section>
  <section className="quote shell" id="resources"><blockquote>“OmniRelay didn’t just automate our workflows. It gave every team the same operating rhythm.”</blockquote><b>Aarav Mehta <small>Chief Operating Officer, Nexora</small></b></section>
  <section className="impact shell section" id="impact"><div className="impact-mark"><span>2%</span><small>OF ELIGIBLE OMNIRELAY REVENUE</small></div><div className="impact-copy"><span className="eyebrow">THE AARIV IMPACT FUND</span><h2>Growth should create<br/><em>good beyond business.</em></h2><p>OmniRelay pledges 2% of eligible revenue to social-impact initiatives that help people access care, opportunity and essential support. Every contribution will be recorded transparently as the programme matures.</p><a href="/about#impact">How the pledge works ↗</a></div><aside><article><b>01</b><span>Separate impact ledger</span></article><article><b>02</b><span>Verified beneficiaries and partners</span></article><article><b>03</b><span>Public annual impact reporting</span></article><small>This is a voluntary social-impact pledge. It is not represented as statutory CSR unless formally qualified and verified.</small></aside></section>
  <section className="cta shell" id="demo"><Mark/><div><span className="eyebrow">READY TO BUILD MOMENTUM?</span><h2>One intelligent system.<br/><em>Limitless possibility.</em></h2></div><aside><p>See how OmniRelay can unify your conversations, workflows and intelligence.</p><a className="btn dark" href="mailto:hello@omnirelay.ai">Book your demo ↗</a></aside></section>
  <footer><div className="shell foot"><div><Logo/><p>The AI business operating system built for infinite momentum.</p></div><div><b>PLATFORM</b><a href="#platform">Overview</a><a href="#solutions">Conversations</a><a href="#solutions">Automation</a></div><div><b>COMPANY</b><a href="/about">About us</a><a href="#impact">Aariv Impact Fund</a><a href="#demo">Contact</a></div><div><b>LEGAL</b><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a><a href="/data-deletion">Data Deletion</a></div></div><div className="shell copyright">© 2026 OmniRelay. All rights reserved.<span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/data-deletion">Data deletion</a></span></div></footer>
 </main>
}
