"use client";

import { useEffect, useState } from "react";
import { Brand } from "@/components/brand";
import { createClient } from "@/lib/supabase/client";

type Booking = { booking_reference:string;slug:string;resource_id:string;location_id:string;service_id:string;customer_name:string;starts_at:string;ends_at:string;status:string;service:string;location:string;provider:string;business:string;timezone:string };
type Slot={starts_at:string;label:string};
function dateKey(value:Date){const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(value);const g=(t:string)=>p.find((i)=>i.type===t)?.value??"";return `${g("year")}-${g("month")}-${g("day")}`}

export function BookingManager({reference,token}:{reference:string;token:string}) {
  const [booking,setBooking]=useState<Booking|null>(null);const [message,setMessage]=useState(reference&&token?"":"This booking link is incomplete.");const [busy,setBusy]=useState(Boolean(reference&&token));const [reschedule,setReschedule]=useState(false);const [date,setDate]=useState(dateKey(new Date()));const [slots,setSlots]=useState<Slot[]>([]);const [slot,setSlot]=useState("");
  const dates=Array.from({length:14},(_,index)=>{const value=new Date(`${dateKey(new Date())}T00:00:00+05:30`);value.setDate(value.getDate()+index);return value});
  useEffect(()=>{if(!reference||!token)return;fetch("/api/public-booking/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"lookup",reference,token})}).then(async(response)=>({response,result:await response.json() as {booking?:Booking;error?:string}})).then(({response,result})=>{if(!response.ok||!result.booking)setMessage(result.error||"Unable to access this booking.");else setBooking(result.booking);setBusy(false)}).catch(()=>{setMessage("Unable to access this booking.");setBusy(false)})},[reference,token]);
  useEffect(()=>{if(!booking||!reschedule)return;createClient().rpc("get_public_booking_slots",{p_slug:booking.slug,p_service_id:booking.service_id,p_location_id:booking.location_id,p_resource_id:booking.resource_id,p_date:date}).then(({data,error})=>{if(error)setMessage(error.message);else setSlots((data as Slot[])??[])})},[booking,date,reschedule]);
  async function cancel(){if(!booking)return;setBusy(true);const response=await fetch("/api/public-booking/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel",reference,token})});if(!response.ok){const result=await response.json() as {error?:string};setMessage(result.error||"Unable to cancel this booking.");setBusy(false)}else window.location.reload()}
  async function move(){if(!slot)return;setBusy(true);const response=await fetch("/api/public-booking/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reschedule",reference,token,starts_at:slot})});if(!response.ok){const result=await response.json() as {error?:string};setMessage(result.error||"Unable to reschedule this booking.");setBusy(false)}else window.location.reload()}
  return <main className="booking-public manage-booking min-h-screen bg-[radial-gradient(circle_at_12%_0%,#dff7f2,transparent_25%),#f5f7fb]"><header className="mx-auto flex w-full max-w-3xl items-center justify-between px-5 py-5 sm:px-8"><Brand className="h-10 w-36"/><span className="rounded-full bg-slate-900 px-3 py-1.5 text-xs font-bold tracking-wide text-white">SECURE BOOKING MANAGEMENT</span></header>{busy?<section className="manage-card"><p>Loading your appointment…</p></section>:!booking?<section className="manage-card"><h1>We couldn’t open this booking.</h1><p>{message}</p></section>:<section className="manage-card"><span>BOOKING {booking.booking_reference}</span><h1>{booking.customer_name}</h1><p>Your appointment with {booking.business}</p><div className="manage-summary"><b>{new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(booking.starts_at))}</b><span>{booking.service} · {booking.location}</span><small>{booking.provider}</small><em>{booking.status}</em></div>{["pending","confirmed"].includes(booking.status)&&<div className="manage-actions"><button onClick={()=>{setReschedule(!reschedule);setSlot("");}}>{reschedule?"Keep current time":"Reschedule"}</button><button className="cancel" onClick={cancel}>Cancel appointment</button></div>}{reschedule&&<section className="customer-reschedule"><b>Select a new time</b><div className="public-date-strip">{dates.map((item)=>{const key=dateKey(item);return <button className={date===key?"selected":""} onClick={()=>{setDate(key);setSlot("");setSlots([]);}} key={key}><span>{new Intl.DateTimeFormat("en-IN",{weekday:"short"}).format(item)}</span><b>{item.getDate()}</b></button>})}</div><div className="public-slots">{slots.length?slots.map((item)=><button className={slot===item.starts_at?"selected":""} onClick={()=>setSlot(item.starts_at)} key={item.starts_at}>{item.label}</button>):<span>No times available on this date.</span>}</div><button className="manage-confirm" disabled={!slot||busy} onClick={move}>Confirm new time</button></section>}{message&&<p className="booking-error">{message}</p>}<small className="manage-note">This secure link controls only this appointment. Do not share it publicly.</small></section>}</main>
}
