"use client";
import { useState } from "react";
type Plan={id:string;name:string;monthly_price_paise:number;max_locations:number;max_seats:number;conversations_quota:number};
type RazorpayResult={razorpay_order_id:string;razorpay_payment_id:string;razorpay_signature:string};
type RazorpayOptions={key:string;amount:number;currency:string;order_id:string;name:string;description:string;theme:{color:string};handler:(r:RazorpayResult)=>void;modal:{ondismiss:()=>void}};
declare global{interface Window{Razorpay?:new(o:RazorpayOptions)=>{open:()=>void}}}

export function BillingWorkspace({plans,currentPlan,status,isTest,business}:{plans:Plan[];currentPlan:string|null;status:string;isTest:boolean;business:string}){
 const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
 async function load(){if(window.Razorpay)return;await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error("Secure checkout could not load"));document.head.appendChild(s)});}
 async function choose(plan:Plan){setBusy(plan.id);setMessage("");try{const response=await fetch("/api/billing/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan_id:plan.id})});const order=await response.json();if(!response.ok)throw new Error(order.error||"Checkout could not start");await load();if(!window.Razorpay)throw new Error("Secure checkout is unavailable");new window.Razorpay({key:order.key_id,amount:order.amount,currency:order.currency,order_id:order.order_id,name:"OmniRelay",description:`${order.plan_name} · one month`,theme:{color:"#168de2"},handler:async(result)=>{const verify=await fetch("/api/billing/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(result)});const confirmed=await verify.json();if(!verify.ok){setBusy(null);setMessage(confirmed.error||"Payment verification failed");return;}setMessage(`${confirmed.plan_name} is active. Refreshing your workspace…`);window.setTimeout(()=>window.location.reload(),900)},modal:{ondismiss:()=>setBusy(null)}}).open()}catch(error){setMessage(error instanceof Error?error.message:"Checkout could not start");setBusy(null)}}
 return <><div className="billing-mode"><div><b>{isTest?"Razorpay test checkout":"Secure Razorpay checkout"}</b><span>{isTest?"No real money will be charged while test keys are active.":"UPI, cards and netbanking are handled by Razorpay."}</span></div><i>{isTest?"TEST MODE":"LIVE"}</i></div>{message&&<div className="billing-message" role="status">{message}</div>}<div className="plan-grid">{plans.map(plan=><article className={plan.id===currentPlan?"current":""} key={plan.id}><span>{plan.id===currentPlan?status.toUpperCase():"MONTHLY"}</span><h3>{plan.name}</h3><b>₹{plan.monthly_price_paise/100}<small>/month</small></b><ul><li>{plan.max_locations} locations</li><li>{plan.max_seats} team seats</li><li>{plan.conversations_quota.toLocaleString("en-IN")} conversations</li></ul><button disabled={busy!==null} onClick={()=>choose(plan)}>{busy===plan.id?"Opening secure checkout…":plan.id===currentPlan&&status==="active"?"Renew this plan":`Choose ${plan.name}`}</button></article>)}</div><p className="billing-footnote">{business} is charged for one month after verified payment. Automatic recurring debit will be enabled only after Razorpay live-account approval.</p></>
}
