"use client";

type Usage={message_category:string;delivery_status:string;estimated_total_paise:number|string;occurred_at:string};
type Rate={message_category:string;base_rate_paise:number|string;source_version:string;verification_status:string};
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(value/100);

export function BillingControls({usage,rates}:{usage:Usage[];rates:Rate[]}){
  const total=usage.reduce((sum,row)=>sum+Number(row.estimated_total_paise||0),0);
  const delivered=usage.filter(row=>row.delivery_status==="delivered").length;
  const exportStatement=()=>{const rows=[["Date","Category","Outcome","Estimated INR"],...usage.map(row=>[new Date(row.occurred_at).toISOString(),row.message_category,row.delivery_status,(Number(row.estimated_total_paise||0)/100).toFixed(2)])];const blob=new Blob([rows.map(row=>row.join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="omnirelay-shadow-statement.csv";link.click();URL.revokeObjectURL(url)};
  return <section className="billing-controls" aria-label="Shadow billing controls"><header><div><span className="app-eyebrow">BILLING CONTROLS</span><h2>Ready for reconciliation, locked from charging</h2><p>Build the evidence first. Wallet top-ups, rate activation and AI creative capture remain disabled.</p></div><b>SHADOW LOCKED</b></header><div className="wallet-summary"><article><span>Daily spend estimate</span><b>{money(total)}</b><small>{usage.length} observed records</small></article><article><span>Delivered outcomes</span><b>{delivered}</b><small>Of {usage.length} observed messages</small></article><article><span>Rate cards</span><b>{rates.length}</b><small>Draft / verified only; none active</small></article><article><span>Reconciliation</span><b>Not started</b><small>Await Meta bill + Razorpay settlement</small></article></div><div className="billing-ledger operational-grid"><article><span>OWNER RATE-CARD CONTROL</span><h3>Source and version tracked</h3>{rates.length?rates.map(rate=><div className="billing-row flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 p-3 bg-slate-50 sm:bg-transparent rounded-xl sm:rounded-none" key={rate.message_category}><div className="min-w-0"><b className="text-sm text-slate-800">{rate.message_category}</b><small className="block text-xs text-slate-500">{rate.source_version}</small></div><div className="flex items-center gap-3 self-end sm:self-auto"><span className="font-bold text-slate-900">{money(Number(rate.base_rate_paise))}</span><i className="pending rounded-full px-2.5 py-1 text-xs font-bold uppercase">{rate.verification_status}</i></div></div>):<p>No planning rate cards yet.</p>}<small>Owner staging is audit-only. Activation remains disabled.</small></article><article><span>MONTHLY STATEMENT</span><h3>Export shadow evidence</h3><p>Download category, delivery outcome and daily estimated usage. It is not an invoice.</p><button type="button" className="billing-control-button min-h-[44px] w-full sm:w-auto px-4 cursor-pointer" onClick={exportStatement}>Export CSV statement</button><small>Wallet top-up, invoice issue and Razorpay capture are disabled.</small></article><article><span>AI CREATIVE LEDGER</span><h3>Reserve → capture → release</h3><p>The data model is ready for a future controlled creative workflow.</p><i className="pending">disabled</i><small>No generation request can reserve or capture money in pilot mode.</small></article><article><span>RECONCILIATION DESK</span><h3>Three-way monthly comparison</h3><p>Compare Meta delivered-message bill, Razorpay settlement and OmniRelay usage ledger before any clinic is charged.</p><i className="pending">awaiting evidence</i></article></div></section>;
}
