"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Patient={id:string;full_name:string;phone:string|null;care_communications_consent:boolean};
type Medicine={id:string;medicine_name:string;dosage:string|null;frequency:string;duration:string|null;instructions:string|null};
type Prescription={id:string;patient_id:string;prescription_number:string;items:Medicine[]};
type Appointment={id:string;patient_id:string|null;resource_id:string|null;location_id:string|null;customer_name:string;starts_at:string;status:string;follow_up_at:string|null;follow_up_note:string|null};
type Option={id:string;name:string};
const dayKey=(value:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date(value));
const toIso=(date:string,time="09:00")=>new Date(`${date}T${time}:00+05:30`).toISOString();
const addDays=(date:string,days:number)=>{const value=new Date(`${date}T00:00:00+05:30`);value.setUTCDate(value.getUTCDate()+days);return dayKey(value)};
const nextDailyRun=(date:string,time:string)=>{let candidate=date;while(new Date(toIso(candidate,time)).getTime()<Date.now()+60_000)candidate=addDays(candidate,1);return toIso(candidate,time)};

export function FollowUpDesk({organizationId,patients,prescriptions,appointments,resources,locations,children}:{organizationId:string;patients:Patient[];prescriptions:Prescription[];appointments:Appointment[];resources:Option[];locations:Option[];children:React.ReactNode}){
 const router=useRouter(),today=dayKey(new Date());
 const [view,setView]=useState<"desk"|"detail">("desk"),[date,setDate]=useState(today),[resourceId,setResourceId]=useState(""),[locationId,setLocationId]=useState(""),[working,setWorking]=useState(""),[notice,setNotice]=useState(""),[medicineFor,setMedicineFor]=useState<Appointment|null>(null),[prescriptionId,setPrescriptionId]=useState(""),[medicineId,setMedicineId]=useState(""),[time,setTime]=useState("09:00"),[endsOn,setEndsOn]=useState("");
 const patientMap=useMemo(()=>new Map(patients.map(patient=>[patient.id,patient])),[patients]);
 const rows=useMemo(()=>appointments.filter(item=>item.patient_id&&dayKey(item.starts_at)===date&&["confirmed","arrived","in_consultation","completed"].includes(item.status)&&(!resourceId||item.resource_id===resourceId)&&(!locationId||item.location_id===locationId)),[appointments,date,resourceId,locationId]);
 const selectedPatient=medicineFor?.patient_id?patientMap.get(medicineFor.patient_id):undefined;
 const patientPrescriptions=selectedPatient?prescriptions.filter(item=>item.patient_id===selectedPatient.id):[];
 const selectedPrescription=patientPrescriptions.find(item=>item.id===prescriptionId);
 const selectedMedicine=selectedPrescription?.items.find(item=>item.id===medicineId);
 async function saveFollowUp(appointment:Appointment,days:number){
  if(!appointment.patient_id)return;setWorking(appointment.id);setNotice("");
  const followUpDate=addDays(date,days);const {error}=await createClient().rpc("set_appointment_follow_up",{p_organization_id:organizationId,p_appointment_id:appointment.id,p_follow_up_at:toIso(followUpDate),p_note:`Follow-up planned ${days} days after visit.`});
  setWorking("");if(error)setNotice(error.message);else{setNotice(`${appointment.customer_name}: follow-up set for ${followUpDate}.`);router.refresh();}
 }
 async function saveMedication(event:React.FormEvent){
  event.preventDefault();if(!medicineFor?.patient_id||!selectedMedicine||working)return;setWorking(medicineFor.id);setNotice("");
  const response=await fetch("/api/care-reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:medicineFor.patient_id,appointmentId:medicineFor.id,prescriptionId,prescriptionItemId:medicineId,reminderType:"medication",title:`${selectedMedicine.medicine_name} reminder`,instructions:selectedMedicine.instructions,scheduleKind:"daily",timeOfDay:time,startsOn:date,endsOn:endsOn||null,nextRunAt:nextDailyRun(date,time),channel:"whatsapp"})});
  const result=await response.json().catch(()=>({}));setWorking("");if(!response.ok){setNotice(result.error??"Medication reminder could not be scheduled.");return}setNotice(result.warning??`${selectedMedicine.medicine_name} reminder scheduled for ${medicineFor.customer_name}; appointment marked arrived.`);setMedicineFor(null);setPrescriptionId("");setMedicineId("");router.refresh();
 }
  const openMedication=(appointment:Appointment)=>{setMedicineFor(appointment);const first=prescriptions.find(item=>item.patient_id===appointment.patient_id);setPrescriptionId(first?.id??"");setMedicineId("");setTime("09:00");setEndsOn("");};
 return <main className="mx-auto grid max-w-7xl gap-5 pb-12">
  <section className="overflow-hidden rounded-3xl bg-[radial-gradient(circle_at_82%_12%,rgba(51,198,221,.42),transparent_26%),linear-gradient(115deg,#06182e,#0b4263)] px-6 py-7 text-white shadow-[0_18px_48px_rgba(7,19,38,.14)] sm:px-8"><span className="or-type-label text-teal-300">CONTINUED CARE</span><h1 className="or-type-page mt-3">Follow-up Desk</h1><p className="mt-3 max-w-2xl text-base leading-7 text-slate-200">Plan each completed visit from one session list. The clinical record and full reminder controls remain available when needed.</p></section>
  <div className="flex flex-wrap gap-2 rounded-2xl border border-border bg-white p-2 shadow-sm"><button className={`min-h-10 rounded-xl px-4 text-sm font-bold ${view==="desk"?"bg-primary text-white":"text-slate-600 hover:bg-slate-50"}`} onClick={()=>setView("desk")}>Today&apos;s Follow-up Desk</button><button className={`min-h-10 rounded-xl px-4 text-sm font-bold ${view==="detail"?"bg-primary text-white":"text-slate-600 hover:bg-slate-50"}`} onClick={()=>setView("detail")}>Care Plan & Clinical Detail</button></div>
  {view==="detail"?children:<>
   <section className="grid gap-3 rounded-2xl border border-border bg-white p-4 shadow-sm md:grid-cols-3"><label className="grid gap-1 text-sm font-bold text-slate-700">Date<input className="min-h-11 rounded-xl border border-border px-3 font-normal" type="date" value={date} onChange={event=>setDate(event.target.value)}/></label>{resources.length>1&&<label className="grid gap-1 text-sm font-bold text-slate-700">Doctor<select className="min-h-11 rounded-xl border border-border px-3 font-normal" value={resourceId} onChange={event=>setResourceId(event.target.value)}><option value="">All doctors</option>{resources.map(resource=><option key={resource.id} value={resource.id}>{resource.name}</option>)}</select></label>}<label className="grid gap-1 text-sm font-bold text-slate-700">Chamber<select className="min-h-11 rounded-xl border border-border px-3 font-normal" value={locationId} onChange={event=>setLocationId(event.target.value)}><option value="">All chambers</option>{locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label></section>
  <section className="overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><header className="flex flex-col gap-2 border-b border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><span className="app-eyebrow">SESSION LIST</span><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">{rows.length} booked patient{rows.length===1?"":"s"}</h2></div><span className="text-sm text-slate-500">Confirmed through completed visits; no-shows and cancellations stay excluded</span></header>{rows.length===0?<p className="p-6 text-sm text-slate-600">No booked patients match this session. No-shows and cancelled bookings are intentionally excluded.</p>:<div className="divide-y divide-border">{rows.map(appointment=>{const patient=appointment.patient_id?patientMap.get(appointment.patient_id):undefined;return <article className="grid gap-3 p-5 lg:grid-cols-[minmax(190px,1fr)_auto_auto] lg:items-center" key={appointment.id}><div><b className="block text-base text-slate-900">{appointment.customer_name}</b><span className="mt-1 block text-sm text-slate-500">{resources.find(resource=>resource.id===appointment.resource_id)?.name??"Provider"} · {appointment.status.replaceAll("_"," ")}</span>{!patient?.care_communications_consent&&<small className="mt-2 block font-medium text-amber-700">WhatsApp needs care consent</small>}{appointment.follow_up_at&&<small className="mt-2 block font-medium text-emerald-700">Follow-up planned: {dayKey(appointment.follow_up_at)}</small>}</div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-slate-600">Follow-up</span>{[5,10,15,30].map(days=><button className="min-h-10 rounded-xl border border-border px-3 text-sm font-bold text-primary hover:border-primary hover:bg-primary/5" disabled={working===appointment.id} key={days} onClick={()=>saveFollowUp(appointment,days)}>{days}D</button>)}<button className="min-h-10 rounded-xl border border-border px-3 text-sm font-bold text-slate-700" disabled={working===appointment.id} onClick={()=>{const custom=window.prompt("Follow-up after how many days?");const days=Number(custom);if(Number.isInteger(days)&&days>0)void saveFollowUp(appointment,days);}}>Custom</button></div><button className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-white hover:bg-primary/90" disabled={working===appointment.id||!patient} onClick={()=>openMedication(appointment)}>Medication reminders</button></article>})}</div>}</section>
   {notice&&<p className="rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm font-medium text-sky-900" role="status">{notice}</p>}
  </>}
  {medicineFor&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><form className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl" onSubmit={saveMedication}><header className="flex items-start justify-between gap-4"><div><span className="app-eyebrow">MEDICATION REMINDER</span><h2 className="mt-1 text-xl font-semibold text-slate-900">{medicineFor.customer_name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Select only medicines from an issued prescription. Clinical medicine details cannot be changed here.</p></div><button className="text-2xl text-slate-500" type="button" onClick={()=>setMedicineFor(null)} aria-label="Close">×</button></header><div className="mt-5 grid gap-4"><label className="grid gap-1 text-sm font-bold text-slate-700">Issued prescription<select required className="min-h-11 rounded-xl border border-border px-3 font-normal" value={prescriptionId} onChange={event=>{setPrescriptionId(event.target.value);setMedicineId("")}}><option value="">Select prescription</option>{patientPrescriptions.map(prescription=><option key={prescription.id} value={prescription.id}>{prescription.prescription_number}</option>)}</select></label><label className="grid gap-1 text-sm font-bold text-slate-700">Medicine<select required className="min-h-11 rounded-xl border border-border px-3 font-normal" value={medicineId} onChange={event=>setMedicineId(event.target.value)} disabled={!selectedPrescription}><option value="">Select medicine</option>{selectedPrescription?.items.map(medicine=><option key={medicine.id} value={medicine.id}>{medicine.medicine_name}{medicine.dosage?` · ${medicine.dosage}`:""}{medicine.frequency?` · ${medicine.frequency}`:""}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold text-slate-700">Daily reminder time<input required className="min-h-11 rounded-xl border border-border px-3 font-normal" type="time" value={time} onChange={event=>setTime(event.target.value)}/></label><label className="grid gap-1 text-sm font-bold text-slate-700">Stop date <span className="font-normal text-slate-500">optional</span><input className="min-h-11 rounded-xl border border-border px-3 font-normal" type="date" min={date} value={endsOn} onChange={event=>setEndsOn(event.target.value)}/></label></div>{selectedMedicine&&<p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><b>{selectedMedicine.medicine_name}</b>{selectedMedicine.instructions?` — ${selectedMedicine.instructions}`:""}</p>}<button className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-white disabled:opacity-50" disabled={!selectedMedicine||working===medicineFor.id}>{working===medicineFor.id?"Scheduling…":"Schedule medication reminder"}</button></div></form></div>}
 </main>;
}
