"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Brand } from "@/components/brand";
import { createClient } from "@/lib/supabase/client";

type Payment={mode:"full_online"|"deposit_online";amount_paise:number;currency:string;status:string;paid_at:string|null};
type Appointment={id:string;starts_at:string;ends_at:string;status:string;payment_status:string;payment:Payment|null;service_id:string;location_id:string;resource_id:string;service:string;location:string;provider:string;slug:string};
type PrescriptionItem={medicine_name:string;dosage:string;frequency:string;duration:string;instructions:string};
type Prescription={id:string;prescription_number:string;issued_at:string;diagnosis:string|null;advice:string|null;tests_requested:string|null;follow_up_at:string|null;items:PrescriptionItem[]};
type Visit={id:string;occurred_at:string;encounter_type:string;follow_up_at:string|null;follow_up_status:string|null};
type CarePlan={id:string;title:string;plan_type:string;status:string;starts_on:string;target_date:string|null;next_review_at:string|null;reminder_status:string|null;reminder_scheduled_for:string|null};
type DataRequest={id:string;reference:string;request_type:string;status:string;created_at:string};
type Portal={scope:"bookings"|"records"|"all";expires_at:string;business:string;patient:{full_name:string;age:number|null;locality:string|null;pincode:string|null};appointments:Appointment[];visits:Visit[];prescriptions:Prescription[];care_plans:CarePlan[];data_requests:DataRequest[]};
type Slot={starts_at:string;label:string};

const format=(value:string,withTime=true)=>new Intl.DateTimeFormat("en-IN",withTime?{weekday:"short",day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}:{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(value));
function dateKey(value:Date){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(value);const get=(type:string)=>parts.find(x=>x.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`}

export function PatientPortal({token}:{token:string}) {
  const [data,setData]=useState<Portal|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(true);
  const [moving,setMoving]=useState<Appointment|null>(null); const [date,setDate]=useState(dateKey(new Date())); const [slots,setSlots]=useState<Slot[]>([]); const [selected,setSelected]=useState("");
  const [requestOpen,setRequestOpen]=useState(false); const [requestType,setRequestType]=useState("access_export"); const [requestSummary,setRequestSummary]=useState(""); const [requestMessage,setRequestMessage]=useState("");
  const dates=useMemo(()=>Array.from({length:14},(_,i)=>{const d=new Date(`${dateKey(new Date())}T00:00:00+05:30`);d.setDate(d.getDate()+i);return d}),[]);
  const load=useCallback(async()=>{setBusy(true);const response=await fetch(`/api/patient/portal?token=${encodeURIComponent(token)}`,{cache:"no-store",referrerPolicy:"no-referrer",credentials:"same-origin"});const body=await response.json();if(!response.ok){setError(body.error);setData(null)}else{setData(body);setError("");window.history.replaceState({},"","/patient")}setBusy(false)},[token]);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(token){void load();return}setError("This secure link is incomplete.");setBusy(false)},0);return()=>window.clearTimeout(timer)},[load,token]);
  useEffect(()=>{if(!moving)return;const timer=window.setTimeout(()=>{setSlots([]);setSelected("")},0);createClient().rpc("get_public_booking_slots",{p_slug:moving.slug,p_service_id:moving.service_id,p_location_id:moving.location_id,p_resource_id:moving.resource_id,p_date:date}).then(({data,error})=>{if(error)setError(error.message);else setSlots((data as Slot[])??[])});return()=>window.clearTimeout(timer)},[moving,date]);
  async function act(action:"cancel"|"reschedule",appointment:Appointment,startsAt?:string){setBusy(true);setError("");const response=await fetch("/api/patient/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,appointmentId:appointment.id,startsAt}),referrerPolicy:"no-referrer",credentials:"same-origin"});const body=await response.json();if(!response.ok){setError(body.error);setBusy(false);return}setMoving(null);await load()}
  async function signOut(){setBusy(true);await fetch("/api/patient/portal",{method:"DELETE",credentials:"same-origin",referrerPolicy:"no-referrer"});setData(null);setError("You have signed out. Request a fresh secure link in WhatsApp whenever you need access.");setBusy(false)}
  async function submitDataRequest(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setRequestMessage("");const response=await fetch("/api/patient/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"data_request",requestType,summary:requestSummary}),referrerPolicy:"no-referrer",credentials:"same-origin"});const body=await response.json();if(!response.ok){setError(body.error??"Request could not be submitted.");setBusy(false);return}setRequestOpen(false);setRequestSummary("");setRequestMessage(`${body.request.reference} submitted securely.`);await load()}
  const upcoming=(data?.appointments??[]).filter(a=>new Date(a.starts_at)>new Date()&&!['cancelled','completed','no_show'].includes(a.status)).sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at));
  const past=(data?.appointments??[]).filter(a=>new Date(a.starts_at)<=new Date()||['cancelled','completed','no_show'].includes(a.status)).slice(0,12);

  return <main className="booking-public patient-portal min-h-screen bg-[radial-gradient(circle_at_12%_0%,#dff7f2,transparent_25%),#f5f7fb]"><header className="mx-auto flex w-full max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><Brand className="h-10 w-36"/><span className="rounded-full bg-slate-900 px-3 py-1.5 text-xs font-bold tracking-wide text-white">PRIVATE · 15-MINUTE ACCESS</span></header>
    <section className="patient-portal-shell">
      {busy&&!data?<div className="portal-state"><i>○</i><h1>Opening your secure portal…</h1></div>:error&&!data?<div className="portal-state expired"><i>!</i><h1>Link unavailable</h1><p>{error}</p><small>Return to WhatsApp and request a fresh link using option 2 or 3.</small></div>:data&&<>
        <header className="portal-welcome"><div><span>VERIFIED WHATSAPP ACCESS</span><h1>Hello, {data.patient.full_name}.</h1><p>{data.business} shared only the records allowed for this session.</p></div><aside><b>Secure session</b><span>Expires {new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(data.expires_at))}</span><small>Do not forward this link.</small><button onClick={signOut}>Sign out now</button></aside></header>
        {error&&<p className="portal-error">{error}</p>}
        {data.scope!=="records"&&<section className="portal-section"><header><div><span>UPCOMING</span><h2>Your appointments</h2></div><b>{upcoming.length}</b></header>{upcoming.length===0?<p className="portal-empty">No upcoming appointment is linked to this patient profile.</p>:upcoming.map(a=><article className="portal-appointment" key={a.id}><time>{format(a.starts_at)}</time><div><b>{a.service}</b><span>{a.location} · {a.provider}</span><small>{a.status}</small>{a.payment?<em className={`portal-payment ${a.payment.status}`}>{a.payment.mode==="deposit_online"?"Deposit":"Online payment"}: ₹{(a.payment.amount_paise/100).toLocaleString("en-IN")} · {a.payment.status}</em>:<em className="portal-payment clinic">Payment at clinic · {a.payment_status.replaceAll("_"," ")}</em>}</div><nav><button onClick={()=>{setMoving(a);setDate(dateKey(new Date()));}}>Reschedule</button><button className="danger" onClick={()=>confirm("Cancel this appointment?")&&act("cancel",a)}>Cancel</button></nav></article>)}</section>}
        {moving&&<section className="portal-section portal-reschedule"><header><div><span>NEW TIME</span><h2>Reschedule {moving.service}</h2></div><button onClick={()=>setMoving(null)}>Close</button></header><div className="public-date-strip">{dates.map(d=>{const key=dateKey(d);return <button className={key===date?"selected":""} onClick={()=>setDate(key)} key={key}><span>{new Intl.DateTimeFormat("en-IN",{weekday:"short"}).format(d)}</span><b>{d.getDate()}</b></button>})}</div><div className="public-slots">{slots.length?slots.map(s=><button className={selected===s.starts_at?"selected":""} onClick={()=>setSelected(s.starts_at)} key={s.starts_at}>{s.label}</button>):<span>No free times on this date.</span>}</div><button className="manage-confirm" disabled={!selected||busy} onClick={()=>act("reschedule",moving,selected)}>Confirm new time</button></section>}
        {data.scope!=="records"&&past.length>0&&<section className="portal-section"><header><div><span>HISTORY</span><h2>Past bookings</h2></div></header>{past.map(a=><article className="portal-history" key={a.id}><b>{a.service}</b><span>{format(a.starts_at)} · {a.location}</span><small>{a.status}</small></article>)}</section>}
        {data.scope!=="bookings"&&<section className="portal-section"><header><div><span>APPROVED RECORDS</span><h2>Visits and prescriptions</h2></div><b>{data.prescriptions.length}</b></header>{data.visits.map(v=><article className="portal-history" key={v.id}><b>{v.encounter_type||"Clinic visit"}</b><span>{format(v.occurred_at,false)}</span><small>{v.follow_up_at?`Follow-up ${format(v.follow_up_at,false)}`:"No follow-up recorded"}</small></article>)}{data.prescriptions.length===0&&data.visits.length===0?<p className="portal-empty">No issued prescription or approved visit summary is available.</p>:data.prescriptions.map(rx=><article className="portal-prescription" key={rx.id}><header><div><span>PRESCRIPTION</span><b>{rx.prescription_number||format(rx.issued_at,false)}</b></div><time>{format(rx.issued_at,false)}</time></header>{rx.diagnosis&&<p><b>Recorded diagnosis</b>{rx.diagnosis}</p>}<ul>{rx.items.map((item,i)=><li key={i}><b>{item.medicine_name}</b><span>{[item.dosage,item.frequency,item.duration].filter(Boolean).join(" · ")}</span>{item.instructions&&<small>{item.instructions}</small>}</li>)}</ul>{rx.advice&&<p><b>Advice</b>{rx.advice}</p>}</article>)}</section>}
        {data.scope!=="bookings"&&<section className="portal-section"><header><div><span>FOLLOW-UP</span><h2>Your care plan</h2></div><b>{data.care_plans.length}</b></header>{data.care_plans.length===0?<p className="portal-empty">No active care-plan follow-up is shared with this profile.</p>:data.care_plans.map(plan=><article className="portal-care-plan" key={plan.id}><div><b>{plan.title}</b><span>{plan.plan_type.replaceAll("_"," ")} · {plan.status}</span></div><aside><b>{plan.next_review_at?format(plan.next_review_at):"No review scheduled"}</b><small>{plan.reminder_status?`Reminder ${plan.reminder_status}`:"No WhatsApp reminder"}</small></aside></article>)}</section>}
        <section className="portal-section portal-data-rights"><header><div><span>PRIVACY & DATA RIGHTS</span><h2>Request access or a change</h2></div><button onClick={()=>setRequestOpen(!requestOpen)}>{requestOpen?"Close":"New request"}</button></header><p className="portal-empty">Ask the clinic for an access/export copy, correction, consent withdrawal or erasure review. Clinical records are never deleted automatically; the clinic first completes identity, legal and care-retention review.</p>{requestMessage&&<p className="portal-request-success">✓ {requestMessage}</p>}{requestOpen&&<form onSubmit={submitDataRequest}><label>Request type<select value={requestType} onChange={e=>setRequestType(e.target.value)}><option value="access_export">Access or export copy</option><option value="correction">Correct my information</option><option value="consent_withdrawal">Withdraw consent</option><option value="erasure">Request erasure review</option></select></label><label>What should the clinic review?<textarea required minLength={5} maxLength={1000} value={requestSummary} onChange={e=>setRequestSummary(e.target.value)} placeholder="Describe the request. Avoid adding new medical details here."/></label><button disabled={busy}>{busy?"Submitting…":"Submit secure request"}</button></form>}{data.data_requests.length>0&&<div className="portal-request-list">{data.data_requests.map(item=><article key={item.id}><div><b>{item.reference}</b><span>{item.request_type.replaceAll("_"," ")}</span></div><em>{item.status.replaceAll("_"," ")}</em><time>{format(item.created_at,false)}</time></article>)}</div>}</section>
        <footer className="portal-privacy"><b>Privacy boundary</b><span>WhatsApp verified possession of the registered number. Staff-only notes are never displayed here. For any mismatch, contact the clinic.</span></footer>
      </>}
    </section>
  </main>;
}
