import { NextResponse } from "next/server";

export async function GET() {
  const env = process.env;
  
  const results = {
    SUPABASE_URL: !!env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY: !!env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_SECRET_KEY: !!env.SUPABASE_SECRET_KEY || !!env.SUPABASE_SERVICE_ROLE_KEY,
    RAZORPAY_KEY_ID: !!env.RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: !!env.RAZORPAY_KEY_SECRET,
    RESEND_API_KEY: !!env.RESEND_API_KEY,
    GOOGLE_CLIENT_ID: !!env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: !!env.GOOGLE_CLIENT_SECRET,
    GEMINI_API_KEY: !!env.GEMINI_API_KEY,
    META_APP_ID: !!env.META_APP_ID,
    META_EMBEDDED_SIGNUP_CONFIG_ID: !!env.META_EMBEDDED_SIGNUP_CONFIG_ID,
    WHATSAPP_VERIFY_TOKEN: !!env.WHATSAPP_VERIFY_TOKEN,
    WHATSAPP_APP_SECRET: !!env.WHATSAPP_APP_SECRET,
  };

  return NextResponse.json(results);
}
