-- A doctor may appear on several rows: one row per chamber/session.  This keeps
-- preview-first onboarding while avoiding one-provider-at-a-time configuration.
create or replace function public.import_doctor_roster_v2(
  p_organization_id uuid, p_rows jsonb, p_commit boolean default false, p_source_format text default 'csv'
) returns jsonb language plpgsql security invoker set search_path='' as $$
declare item jsonb; row_number integer:=0; errors jsonb:='[]'::jsonb; normalized jsonb:='[]'::jsonb; weekdays jsonb;
  doctor_name text; specialization text; department_name text; chamber_name text; start_text text; end_text text; contact_phone text; contact_email text; slot_minutes integer;
  location_id uuid; resource_id uuid; assignment_id uuid; department_id uuid; imported integer:=0; is_new boolean;
begin
  if not private.is_organization_member(p_organization_id,'admin') then raise exception 'Administrator access required' using errcode='42501'; end if;
  if p_source_format not in ('csv','json') or jsonb_typeof(coalesce(p_rows,'null'::jsonb))<>'array' then raise exception 'Invalid roster import'; end if;
  if jsonb_array_length(p_rows) not between 1 and 200 then raise exception 'Import must contain between 1 and 200 rows'; end if;
  for item in select value from jsonb_array_elements(p_rows) loop
    row_number:=row_number+1; doctor_name:=trim(coalesce(item->>'doctor_name','')); specialization:=trim(coalesce(item->>'specialization','')); department_name:=nullif(trim(coalesce(item->>'department','')),''); chamber_name:=trim(coalesce(item->>'chamber','')); start_text:=trim(coalesce(item->>'start_time','')); end_text:=trim(coalesce(item->>'end_time','')); contact_phone:=nullif(trim(coalesce(item->>'contact_phone','')),''); contact_email:=lower(nullif(trim(coalesce(item->>'contact_email','')),'')); weekdays:=coalesce(item->'weekdays','[]'::jsonb);
    begin slot_minutes:=(item->>'slot_duration_minutes')::integer; exception when others then slot_minutes:=0; end;
    select id into location_id from public.business_locations where organization_id=p_organization_id and active and lower(trim(name))=lower(chamber_name) limit 1;
    if char_length(doctor_name) not between 2 and 120 then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','doctor_name','message','Enter a doctor name between 2 and 120 characters.')); end if;
    if specialization='' then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','specialization','message','Specialization is required.')); end if;
    if location_id is null then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','chamber','message','Chamber name does not match an active clinic location.')); end if;
    if start_text !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or end_text !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or start_text>=end_text then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','time','message','Use HH:MM values and ensure end time is later.')); end if;
    if slot_minutes not between 5 and 240 then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','slot_duration_minutes','message','Slot duration must be between 5 and 240 minutes.')); end if;
    if jsonb_typeof(weekdays)<>'array' or jsonb_array_length(weekdays)=0 or exists(select 1 from jsonb_array_elements_text(weekdays) d where d !~ '^[0-6]$') then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','weekdays','message','Choose weekdays using 0 to 6.')); end if;
    if department_name is not null and char_length(department_name)>80 then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','department','message','Department must be 80 characters or fewer.')); end if;
    if contact_email is not null and contact_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','contact_email','message','Enter a valid email address.')); end if;
    if contact_phone is not null and private.normalize_phone_identity(contact_phone) is null then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','contact_phone','message','Enter a valid mobile number.')); end if;
    if exists(select 1 from public.booking_resources r where r.organization_id=p_organization_id and lower(trim(r.name))=lower(doctor_name)) then errors:=errors||jsonb_build_array(jsonb_build_object('row',row_number,'field','doctor_name','message','Doctor already exists; bulk import only creates new doctors.')); end if;
    normalized:=normalized||jsonb_build_array(jsonb_build_object('row',row_number,'doctor_name',doctor_name,'specialization',specialization,'department',department_name,'contact_phone',contact_phone,'contact_email',contact_email,'chamber',chamber_name,'weekdays',weekdays,'start_time',start_text,'end_time',end_text,'slot_duration_minutes',slot_minutes));
  end loop;
  if jsonb_array_length(errors)>0 or not p_commit then return jsonb_build_object('valid',jsonb_array_length(errors)=0,'committed',false,'row_count',jsonb_array_length(p_rows),'rows',normalized,'errors',errors); end if;
  for item in select value from jsonb_array_elements(normalized) loop
    doctor_name:=item->>'doctor_name'; chamber_name:=item->>'chamber'; select id into location_id from public.business_locations where organization_id=p_organization_id and active and lower(trim(name))=lower(chamber_name) limit 1;
    select id into resource_id from public.booking_resources where organization_id=p_organization_id and lower(trim(name))=lower(doctor_name) limit 1; is_new:=resource_id is null;
    if is_new then insert into public.booking_resources(organization_id,location_id,name,resource_type,timezone) select p_organization_id,location_id,doctor_name,'doctor',timezone from public.business_locations where id=location_id returning id into resource_id; insert into public.provider_profiles(resource_id,organization_id,specialization,contact_phone,contact_email,languages) values(resource_id,p_organization_id,item->>'specialization',item->>'contact_phone',item->>'contact_email','{}'::text[]); end if;
    select id into assignment_id from public.provider_location_assignments where organization_id=p_organization_id and resource_id=resource_id and location_id=location_id;
    if assignment_id is null then insert into public.provider_location_assignments(organization_id,resource_id,location_id,active,effective_from,booking_window_days) values(p_organization_id,resource_id,location_id,true,current_date,60) returning id into assignment_id; insert into public.provider_location_services(organization_id,assignment_id,service_id,active) select p_organization_id,assignment_id,id,true from public.organization_services where organization_id=p_organization_id and active and booking_enabled; end if;
    for weekdays in select value from jsonb_array_elements(item->'weekdays') loop insert into public.availability_rules(organization_id,resource_id,location_id,weekday,start_time,end_time,slot_interval_minutes,active,effective_from) values(p_organization_id,resource_id,location_id,(weekdays#>>'{}')::smallint,(item->>'start_time')::time,(item->>'end_time')::time,(item->>'slot_duration_minutes')::integer,true,current_date) on conflict(resource_id,location_id,weekday,start_time,end_time) do update set slot_interval_minutes=excluded.slot_interval_minutes,active=true,effective_from=current_date,effective_to=null,updated_at=now(); end loop;
    department_name:=item->>'department'; if department_name is not null then select id into department_id from public.clinic_departments where organization_id=p_organization_id and lower(trim(name))=lower(department_name) limit 1; if department_id is null then insert into public.clinic_departments(organization_id,name,active,sort_order) values(p_organization_id,department_name,true,999) returning id into department_id; end if; insert into public.provider_departments(organization_id,resource_id,department_id,primary_department) values(p_organization_id,resource_id,department_id,not exists(select 1 from public.provider_departments where organization_id=p_organization_id and resource_id=resource_id)) on conflict(department_id,resource_id) do nothing; end if;
    imported:=imported+1;
  end loop;
  insert into public.doctor_import_jobs(organization_id,source_format,row_count,imported_count,status,payload_hash,created_by) values(p_organization_id,p_source_format,jsonb_array_length(p_rows),imported,'completed',encode(extensions.digest(convert_to(p_rows::text,'UTF8'),'sha256'),'hex'),auth.uid());
  return jsonb_build_object('valid',true,'committed',true,'row_count',jsonb_array_length(p_rows),'imported_count',imported,'errors','[]'::jsonb);
end; $$;
revoke all on function public.import_doctor_roster_v2(uuid,jsonb,boolean,text) from public,anon;
grant execute on function public.import_doctor_roster_v2(uuid,jsonb,boolean,text) to authenticated;
